### ISSUE TITLE
Remove not deleting venv if multiple apps

### ISSUE THREAD

**Issue by sxoi-max** [mx-personal/yggdrasil#12]
Remove does not delete the virtual environment attached to the app when:
- Multiple apps use the same venv
- And all the apps are removed as part of the current run
--> Should add a condition to remove venv if all apps using it are removed in the same run

**Comment by um-en** [comment]
Solved intrinsically through changes on the base settings file (single app with multiple entry points in yaml format) from 2.0-alpha-2
